#ECE2112_PA4

#A. VISAYAS COMMUNICATION DATAFRAME

In [72]:
import pandas as pd
df = pd.read_excel('/content/board2.xlsx')
df

,Name,Gender,Track,Hometown,Math,Electronics,GEAS,Communication
0,S1,Male,Instrumentation,Luzon,58,89,75,78
1,S2,Female,Communication,Mindanao,52,75,90,52
2,S3,Female,Instrumentation,Mindanao,83,74,77,57
3,S4,Male,Instrumentation,Visayas,65,58,91,68
4,S5,Male,Communication,Luzon,59,86,43,88
5,S6,Female,Microelectronics,Visayas,88,45,86,83
6,S7,Female,Instrumentation,Luzon,66,60,60,48
7,S8,Male,Instrumentation,Luzon,49,81,64,53
8,S9,Male,Instrumentation,Luzon,50,36,63,42
9,S10,Male,Microelectronics,Mindanao,80,84,61,44
10,S11,Female,Communication,Visayas,48,56,48,67
11,S12,Male,Communication,Visayas,89,67,84,64
12,S13,Female,Microelectronics,Luzon,88,35,83,43
13,S14,Female,Microelectronics,Luzon,83,77,89,73
14,S15,Female,Microelectronics,Mindanao,69,41,40,86
15,S16,Female,Communication,Luzon,71,70,87,81
16,S17,Female,Microelectronics,Mindanao,81,79,77,45
17,S18,Male,Communication,Visayas,81,40,81,52
18,S19,Male,Microelectronics,Luzon,79,63,79,71
19,S20,Female,Communication,Mindanao,59,60,62,85
20,S21,Female,Microelectronics,Visayas,83,51,68,72
21,S22,Female,Communication,Visayas,64,39,89,58
22,S23,Male,Instrumentation,Luzon,84,70,74,47
23,S24,Female,Microelectronics,Visayas,85,45,60,41
24,S25,Male,Communication,Luzon,74,91,94,42
25,S26,Female,Instrumentation,Visayas,71,47,83,62
26,S27,Male,Microelectronics,Visayas,70,47,40,86
27,S28,Male,Communication,Visayas,85,53,80,53
28,S29,Male,Instrumentation,Mindanao,73,48,71,62
29,S30,Male,Instrumentation,Luzon,78,81,57,56

In [73]:
VisComm = df.copy()

In [74]:
#average computation
Average = VisComm.mean(axis = 1, numeric_only = True)
print(Average)

0     75.00
1     67.25
2     72.75
3     70.50
4     69.00
5     75.50
6     58.50
7     61.75
8     47.75
9     67.25
10    54.75
11    76.00
12    62.25
13    80.50
14    59.00
15    77.25
16    70.50
17    63.50
18    73.00
19    66.50
20    68.50
21    62.50
22    68.75
23    57.75
24    75.25
25    65.75
26    60.75
27    67.75
28    63.50
29    68.00
dtype: float64

In [75]:
VisComm['Average'] = Average
VisComm = VisComm.loc[(VisComm['Hometown']=='Visayas')&(df['Track']=='Communication'),['Name','Gender','Math','Electronics','Average']]
VisComm

   Name  Gender  Math  Electronics  Average
10  S11  Female    48           56    54.75
11  S12    Male    89           67    76.00
17  S18    Male    81           40    63.50
21  S22  Female    64           39    62.50
27  S28    Male    85           53    67.75

In [76]:
VisComm.shape

(5, 5)

#B. VISAYAS FEMALE DATAFRAME

In [80]:
VisFemale = df.copy()
VisFemale['Average'] = Average
VisFemale = VisFemale.loc[(VisFemale['Hometown'] == 'Visayas') &(VisFemale['Gender'] == 'Female'),['Name', 'Track', 'GEAS', 'Electronics', 'Average']]
VisFemale.loc[VisFemale['Average'] >= 60]
VisFemale

   Name             Track  GEAS  Electronics  Average
5    S6  Microelectronics    86           45    75.50
10  S11     Communication    48           56    54.75
20  S21  Microelectronics    68           51    68.50
21  S22     Communication    89           39    62.50
23  S24  Microelectronics    60           45    57.75
25  S26   Instrumentation    83           47    65.75

C. CATEGORY-AVERAGE VISUALIZATION

In [87]:
df_average = df.copy()
df_average['Average'] = Average

track_average = df_average.groupby('Track')['Average'].mean()
gender_average = df_average.groupby('Gender')['Average'].mean()
hometown_average = df_average.groupby('Hometown')['Average'].mean()
print(track_average,
      gender_average,
      hometown_average)

Track
Communication       67.975
Instrumentation     65.225
Microelectronics    67.500
Name: Average, dtype: float64 Gender
Female    66.616667
Male      67.183333
Name: Average, dtype: float64 Hometown
Luzon       68.083333
Mindanao    66.678571
Visayas     65.750000
Name: Average, dtype: float64

In [ ]:
track_average.plot.bar()
gender_average.plot.bar()
hometown_average.plot.bar()